# Generated by Django 4.2 on 2023-05-06 08:44

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0005_alter_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='user/default_image.png', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=5, max_length=5, prefix='', unique=True),
        ),
    ]
