# Generated by Django 4.2 on 2023-05-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0006_alter_user_avatar_alter_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='mood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
